// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/markstgodard/project-mayhem/infrastructure"
)

type FakeProvider struct {
	DestroyStub        func(id string) error
	destroyMutex       sync.RWMutex
	destroyArgsForCall []struct {
		id string
	}
	destroyReturns struct {
		result1 error
	}
}

func (fake *FakeProvider) Destroy(id string) error {
	fake.destroyMutex.Lock()
	fake.destroyArgsForCall = append(fake.destroyArgsForCall, struct {
		id string
	}{id})
	fake.destroyMutex.Unlock()
	if fake.DestroyStub != nil {
		return fake.DestroyStub(id)
	} else {
		return fake.destroyReturns.result1
	}
}

func (fake *FakeProvider) DestroyCallCount() int {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return len(fake.destroyArgsForCall)
}

func (fake *FakeProvider) DestroyArgsForCall(i int) string {
	fake.destroyMutex.RLock()
	defer fake.destroyMutex.RUnlock()
	return fake.destroyArgsForCall[i].id
}

func (fake *FakeProvider) DestroyReturns(result1 error) {
	fake.DestroyStub = nil
	fake.destroyReturns = struct {
		result1 error
	}{result1}
}

var _ infrastructure.Provider = new(FakeProvider)
