// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/markstgodard/project-mayhem/infrastructure"
)

type FakeDeployment struct {
	ListVMsStub        func() (infrastructure.VMs, error)
	listVMsMutex       sync.RWMutex
	listVMsArgsForCall []struct{}
	listVMsReturns     struct {
		result1 infrastructure.VMs
		result2 error
	}
}

func (fake *FakeDeployment) ListVMs() (infrastructure.VMs, error) {
	fake.listVMsMutex.Lock()
	fake.listVMsArgsForCall = append(fake.listVMsArgsForCall, struct{}{})
	fake.listVMsMutex.Unlock()
	if fake.ListVMsStub != nil {
		return fake.ListVMsStub()
	} else {
		return fake.listVMsReturns.result1, fake.listVMsReturns.result2
	}
}

func (fake *FakeDeployment) ListVMsCallCount() int {
	fake.listVMsMutex.RLock()
	defer fake.listVMsMutex.RUnlock()
	return len(fake.listVMsArgsForCall)
}

func (fake *FakeDeployment) ListVMsReturns(result1 infrastructure.VMs, result2 error) {
	fake.ListVMsStub = nil
	fake.listVMsReturns = struct {
		result1 infrastructure.VMs
		result2 error
	}{result1, result2}
}

var _ infrastructure.Deployment = new(FakeDeployment)
