// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/markstgodard/project-mayhem/infrastructure"
)

type FakeDeployment struct {
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct{}
	nameReturns     struct {
		result1 string
	}
	ListVMsStub        func() (infrastructure.VMs, error)
	listVMsMutex       sync.RWMutex
	listVMsArgsForCall []struct{}
	listVMsReturns     struct {
		result1 infrastructure.VMs
		result2 error
	}
}

func (fake *FakeDeployment) Name() string {
	fake.nameMutex.Lock()
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct{}{})
	fake.nameMutex.Unlock()
	if fake.NameStub != nil {
		return fake.NameStub()
	} else {
		return fake.nameReturns.result1
	}
}

func (fake *FakeDeployment) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeDeployment) NameReturns(result1 string) {
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeDeployment) ListVMs() (infrastructure.VMs, error) {
	fake.listVMsMutex.Lock()
	fake.listVMsArgsForCall = append(fake.listVMsArgsForCall, struct{}{})
	fake.listVMsMutex.Unlock()
	if fake.ListVMsStub != nil {
		return fake.ListVMsStub()
	} else {
		return fake.listVMsReturns.result1, fake.listVMsReturns.result2
	}
}

func (fake *FakeDeployment) ListVMsCallCount() int {
	fake.listVMsMutex.RLock()
	defer fake.listVMsMutex.RUnlock()
	return len(fake.listVMsArgsForCall)
}

func (fake *FakeDeployment) ListVMsReturns(result1 infrastructure.VMs, result2 error) {
	fake.ListVMsStub = nil
	fake.listVMsReturns = struct {
		result1 infrastructure.VMs
		result2 error
	}{result1, result2}
}

var _ infrastructure.Deployment = new(FakeDeployment)
